// This file is generated by icon spritesheet generator

export const iconNames = [
  "Views",
  "User",
  "Todo",
  "Sprite",
  "Search",
  "OpenNav",
  "NewIssue",
  "Issues",
  "Inbox",
  "InProgress",
  "Filter",
  "Done",
  "CloseButton",
  "CircleDashed",
  "Cancelled",
  "Backlog",
] as const

export type IconName = typeof iconNames[number]
