// This file is generated by icon spritesheet generator

export type IconName =
  | "Views"
  | "User"
  | "Search"
  | "NewIssue"
  | "Issues"
  | "Inbox"
  | "Filter"
  | "CloseButton"
  | "CircleDashed"
  | "Backlog"

export const iconNames = [
  "Views",
  "User",
  "Search",
  "NewIssue",
  "Issues",
  "Inbox",
  "Filter",
  "CloseButton",
  "CircleDashed",
  "Backlog",
] as const
