// This file is generated by icon spritesheet generator

export type IconName =
  | "User"
  | "Inbox"
  | "Filter"
  | "CloseButton"
  | "CircleDashed"

export const iconNames = [
  "User",
  "Inbox",
  "Filter",
  "CloseButton",
  "CircleDashed",
] as const
